spring:
  application:
    name: yongeun-market

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://127.0.0.1:3306/live_chat?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:com.mysql.cj.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:create}
    show-sql: ${SPRING_JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:true}
        dialect: ${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}

  data:
    redis:
      host: localhost
      port: 6379

  cloud:
    aws:
      s3:
        bucket: ${AWS_S3_BUCKET}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mail:
    host: ${SMTP_DOMAIN}
    port: 587
    username: ${SENDER_EMAIL}
    password: ${SENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  config:
    import: optional:file:.env[.properties]

jwt:
  secret: ${JWT_SECRET}
  token-validity-in-seconds: ${JWT_TOKEN_VALIDITY_IN_SECONDS}

password-reset:
  redis-prefix: "password:reset:"
  attempt:
    redis-prefix: "password:reset:attempt:"
  expiry-minutes: 5
